name: Deploy Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Test Linux Script
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x scripts/linux_curl.sh
          # Test script execution
          if [ -f "scripts/linux_curl.sh" ]; then
            echo "Linux script exists"
          else
            echo "Linux script not found"
            exit 1
          fi

      - name: Test macOS Script
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x scripts/macos_curl.sh
          # Test script execution
          if [ -f "scripts/macos_curl.sh" ]; then
            echo "macOS script exists"
          else
            echo "macOS script not found"
            exit 1
          fi

      - name: Test Windows Script
        if: matrix.os == 'windows-latest'
        run: |
          # Test script existence
          if (Test-Path "scripts/windows_irm.ps1") {
            Write-Host "Windows script exists"
          } else {
            Write-Host "Windows script not found"
            exit 1
          }

  deploy:
    needs: test-scripts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./scripts
          publish_branch: gh-pages
